<link rel='stylesheet' id='flatpickr-css' href='{{ asset('frontend/wp-content/plugins/elementor/assets/lib/flatpickr/flatpickr.mineda1.css?ver=4.1.4') }}' media='all' />
<link rel='stylesheet' id='elementor-post-9658-css' href='{{ asset('frontend/wp-content/uploads/elementor/css/post-96585e9f.css?ver=1731750618') }}' media='all' />
<link rel='stylesheet' id='e-animation-bounce-in-css' href='{{ asset('frontend/wp-content/plugins/elementor/assets/lib/animations/styles/e-animation-bounce-in.minf34d.css?ver=3.25.6') }}' media='all' />
<link rel='stylesheet' id='e-animation-slideInRight-css' href='{{ asset('frontend/wp-content/plugins/elementor/assets/lib/animations/styles/slideInRight.minf34d.css?ver=3.25.6') }}' media='all' />
<link rel='stylesheet' id='e-animation-slideInLeft-css' href='{{ asset('frontend/wp-content/plugins/elementor/assets/lib/animations/styles/slideInLeft.minf34d.css?ver=3.25.6') }}' media='all' />
<link rel='stylesheet' id='e-sticky-css' href='{{ asset('frontend/wp-content/plugins/pro-elements/assets/css/modules/sticky.min7ed1.css?ver=3.25.2') }}' media='all' />
<link rel='stylesheet' id='google-fonts-2-css' href='https://fonts.googleapis.com/css?family=PT+Serif%3A100%2C100italic%2C200%2C200italic%2C300%2C300italic%2C400%2C400italic%2C500%2C500italic%2C600%2C600italic%2C700%2C700italic%2C800%2C800italic%2C900%2C900italic&amp;display=swap&amp;ver=6.7' media='all' />
<script src="{{ asset('frontend/wp-content/themes/hello-elementor/assets/js/hello-frontend.minb12b.js?ver=3.1.1') }}" id="hello-theme-frontend-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/pro-elements/assets/lib/smartmenus/jquery.smartmenus.min1576.js?ver=1.2.1') }}" id="smartmenus-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/pro-elements/assets/lib/sticky/jquery.sticky.min7ed1.js?ver=3.25.2') }}" id="e-sticky-js"></script>
<script id="eael-general-js-extra">
var localize = {"ajaxurl":"https:\/\/zaman-it.com\/wp-admin\/admin-ajax.php","nonce":"4a5db88764","i18n":{"added":"Added ","compare":"Compare","loading":"Loading..."},"eael_translate_text":{"required_text":"is a required field","invalid_text":"Invalid","billing_text":"Billing","shipping_text":"Shipping","fg_mfp_counter_text":"of"},"page_permalink":"https:\/\/zaman-it.com\/","cart_redirectition":"","cart_page_url":"","el_breakpoints":{"mobile":{"label":"Mobile Portrait","value":767,"default_value":767,"direction":"max","is_enabled":true},"mobile_extra":{"label":"Mobile Landscape","value":880,"default_value":880,"direction":"max","is_enabled":false},"tablet":{"label":"Tablet Portrait","value":1024,"default_value":1024,"direction":"max","is_enabled":true},"tablet_extra":{"label":"Tablet Landscape","value":1200,"default_value":1200,"direction":"max","is_enabled":false},"laptop":{"label":"Laptop","value":1366,"default_value":1366,"direction":"max","is_enabled":false},"widescreen":{"label":"Widescreen","value":2400,"default_value":2400,"direction":"min","is_enabled":false}}};
</script>
<script src="{{ asset('frontend/wp-content/plugins/essential-addons-for-elementor-lite/assets/front-end/js/view/general.min207c.js?ver=6.0.10') }}" id="eael-general-js"></script>
<script src="{{ asset('frontend/wp-content/uploads/essential-addons-elementor/eael-81060.js?ver=1731349880') }}" id="eael-8-js"></script>
<script id="fca_pc_client_js-js-extra">
var fcaPcEvents = [];
var fcaPcPost = {"title":"Home","type":"page","id":"8","categories":[]};
var fcaPcOptions = {"pixel_types":["Facebook Pixel"],"ajax_url":"https:\/\/zaman-it.com\/wp-admin\/admin-ajax.php","debug":"","edd_currency":"USD","nonce":"5a5fc5adb4","utm_support":"","user_parameters":"","edd_enabled":"","edd_delay":"0","woo_enabled":"","woo_delay":"0","video_enabled":""};
</script>
<script src="{{ asset('frontend/wp-content/plugins/facebook-conversion-pixel/pixel-cat.min7c45.js?ver=3.0.6') }}" id="fca_pc_client_js-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/facebook-conversion-pixel/video0b5e.js?ver=6.7') }}" id="fca_pc_video_js-js"></script>
<script src="../www.google.com/recaptcha/api9f52.js?render=explicit&amp;ver=3.25.2') }}" id="elementor-recaptcha_v3-api-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/elementor/assets/lib/flatpickr/flatpickr.mineda1.js?ver=4.1.4') }}" id="flatpickr-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/pro-elements/assets/js/webpack-pro.runtime.min7ed1.js?ver=3.25.2') }}" id="elementor-pro-webpack-runtime-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/elementor/assets/js/webpack.runtime.minf34d.js?ver=3.25.6') }}" id="elementor-webpack-runtime-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/elementor/assets/js/frontend-modules.minf34d.js?ver=3.25.6') }}" id="elementor-frontend-modules-js"></script>
<script src="{{ asset('frontend/wp-includes/js/dist/hooks.min4fdd.js?ver=4d63a3d491d11ffd8ac6') }}" id="wp-hooks-js"></script>
<script src={{ asset('frontend/"wp-includes/js/dist/i18n.minc33c.js?ver=5e580eb46a90c2b997e6') }}" id="wp-i18n-js"></script>
<script id="wp-i18n-js-after">
wp.i18n.setLocaleData( { 'text direction\u0004ltr': [ 'ltr' ] } );
</script>
<script id="elementor-pro-frontend-js-before">
var ElementorProFrontendConfig = {"ajaxurl":"https:\/\/zaman-it.com\/wp-admin\/admin-ajax.php","nonce":"b3aac9dbdf","urls":{"assets":"https:\/\/zaman-it.com\/wp-content\/plugins\/pro-elements\/assets\/","rest":"https:\/\/zaman-it.com\/wp-json\/"},"settings":{"lazy_load_background_images":false},"popup":{"hasPopUps":true},"shareButtonsNetworks":{"facebook":{"title":"Facebook","has_counter":true},"twitter":{"title":"Twitter"},"linkedin":{"title":"LinkedIn","has_counter":true},"pinterest":{"title":"Pinterest","has_counter":true},"reddit":{"title":"Reddit","has_counter":true},"vk":{"title":"VK","has_counter":true},"odnoklassniki":{"title":"OK","has_counter":true},"tumblr":{"title":"Tumblr"},"digg":{"title":"Digg"},"skype":{"title":"Skype"},"stumbleupon":{"title":"StumbleUpon","has_counter":true},"mix":{"title":"Mix"},"telegram":{"title":"Telegram"},"pocket":{"title":"Pocket","has_counter":true},"xing":{"title":"XING","has_counter":true},"whatsapp":{"title":"WhatsApp"},"email":{"title":"Email"},"print":{"title":"Print"},"x-twitter":{"title":"X"},"threads":{"title":"Threads"}},"facebook_sdk":{"lang":"en_US","app_id":""},"lottie":{"defaultAnimationUrl":"https:\/\/zaman-it.com\/wp-content\/plugins\/pro-elements\/modules\/lottie\/assets\/animations\/default.json"}};
</script>
<script src="{{ asset('frontend/wp-content/plugins/pro-elements/assets/js/frontend.min7ed1.js?ver=3.25.2') }}" id="elementor-pro-frontend-js"></script>
<script src="{{ asset('frontend/wp-includes/js/jquery/ui/core.minb37e.js?ver=1.13.3') }}" id="jquery-ui-core-js"></script>
<script id="elementor-frontend-js-before">
var elementorFrontendConfig = {"environmentMode":{"edit":false,"wpPreview":false,"isScriptDebug":false},"i18n":{"shareOnFacebook":"Share on Facebook","shareOnTwitter":"Share on Twitter","pinIt":"Pin it","download":"Download","downloadImage":"Download image","fullscreen":"Fullscreen","zoom":"Zoom","share":"Share","playVideo":"Play Video","previous":"Previous","next":"Next","close":"Close","a11yCarouselWrapperAriaLabel":"Carousel | Horizontal scrolling: Arrow Left & Right","a11yCarouselPrevSlideMessage":"Previous slide","a11yCarouselNextSlideMessage":"Next slide","a11yCarouselFirstSlideMessage":"This is the first slide","a11yCarouselLastSlideMessage":"This is the last slide","a11yCarouselPaginationBulletMessage":"Go to slide"},"is_rtl":false,"breakpoints":{"xs":0,"sm":480,"md":768,"lg":1025,"xl":1440,"xxl":1600},"responsive":{"breakpoints":{"mobile":{"label":"Mobile Portrait","value":767,"default_value":767,"direction":"max","is_enabled":true},"mobile_extra":{"label":"Mobile Landscape","value":880,"default_value":880,"direction":"max","is_enabled":false},"tablet":{"label":"Tablet Portrait","value":1024,"default_value":1024,"direction":"max","is_enabled":true},"tablet_extra":{"label":"Tablet Landscape","value":1200,"default_value":1200,"direction":"max","is_enabled":false},"laptop":{"label":"Laptop","value":1366,"default_value":1366,"direction":"max","is_enabled":false},"widescreen":{"label":"Widescreen","value":2400,"default_value":2400,"direction":"min","is_enabled":false}},"hasCustomBreakpoints":false},"version":"3.25.6","is_static":false,"experimentalFeatures":{"e_font_icon_svg":true,"additional_custom_breakpoints":true,"container":true,"e_swiper_latest":true,"e_nested_atomic_repeaters":true,"e_optimized_control_loading":true,"e_onboarding":true,"e_css_smooth_scroll":true,"theme_builder_v2":true,"hello-theme-header-footer":true,"home_screen":true,"landing-pages":true,"editor_v2":true,"link-in-bio":true,"floating-buttons":true},"urls":{"assets":"https:\/\/zaman-it.com\/wp-content\/plugins\/elementor\/assets\/","ajaxurl":"https:\/\/zaman-it.com\/wp-admin\/admin-ajax.php","uploadUrl":"https:\/\/zaman-it.com\/wp-content\/uploads"},"nonces":{"floatingButtonsClickTracking":"7426e689e0"},"swiperClass":"swiper","settings":{"page":[],"editorPreferences":[]},"kit":{"active_breakpoints":["viewport_mobile","viewport_tablet"],"global_image_lightbox":"yes","lightbox_enable_counter":"yes","lightbox_enable_fullscreen":"yes","lightbox_enable_zoom":"yes","lightbox_enable_share":"yes","lightbox_title_src":"title","lightbox_description_src":"description","hello_header_logo_type":"logo","hello_header_menu_layout":"horizontal","hello_footer_logo_type":"logo"},"post":{"id":8,"title":"Best%20Web%20Design%20Company%20in%20Bangladesh%20%7C%20Bulk%20SMS%20BD%20%7C%20ZAMAN%20IT","excerpt":"","featuredImage":false}};
</script>
<script src="{{ asset('frontend/wp-content/plugins/elementor/assets/js/frontend.minf34d.js?ver=3.25.6') }}" id="elementor-frontend-js"></script>
<script src="{{ asset('frontend/wp-content/plugins/pro-elements/assets/js/elements-handlers.min7ed1.js?ver=3.25.2') }}" id="pro-elements-handlers-js"></script>
